services:
  ts-wordpress-docker:
    image: tailscale/tailscale:latest
    container_name: ${TS_HOST_CONTAINER_NAME}
    hostname: ${TS_HOST_CONTAINER_NAME}
    environment:
    - TS_AUTHKEY=${TS_OAUTH_KEY}
    - TS_SERVE_CONFIG=/config/ts-wordpress-docker.json
    - TS_EXTRA_ARGS=--advertise-tags=tag:container
    - TS_ACCEPT_DNS=true
    - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/wordpress-test/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  db:
    image: mysql:latest
    network_mode: service:ts-wordpress-docker
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  wordpress:
    depends_on:
      - db
      - ts-wordpress-docker
    image: liquidloose/wordpress-image:latest
    network_mode: service:ts-wordpress-docker
    environment:
      WORDPRESS_DB_HOST: ts-wordpress-docker
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DEBUG: "1" # A non-empty value enables WP_DEBUG in wp-config.php
    volumes:
      - type: bind
        source: ${CLIENT_SOURCE}
        target: ${CONTAINER_TARGET}
    
volumes:
  db_data: {}
