services:
  wordpress-test:
    image: tailscale/tailscale:latest
    container_name: wordpress-test
    hostname: wordpress-test
    environment:
    - TS_AUTHKEY=tskey-auth-key-goes-here
    - TS_EXTRA_ARGS=--advertise-tags=tag:container
    - TS_ACCEPT_DNS=true
    - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/wordpress-test/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  db:
    image: mysql:latest
    network_mode: service:wordpress-test
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: liquidloose/wordpress-image:latest
    network_mode: service:wordpress-test
    environment:
      WORDPRESS_DB_HOST: wordpress-test
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DEBUG: "1" # A non-empty value enables WP_DEBUG in wp-config.php
    volumes:
      - type: bind
        source: ${CLIENT_SOURCE}
        target: ${CONTAINER_TARGET}
    
volumes:
  db_data: {}
